name: PreventObsidianCrash
version: ${project.version}
main: de.tschallacka.preventobsidiancrash.PreventObsidianCrash
api-version: 1.13
description: A plugin to prevent the crash of a very specific setup with a dispenser wit flint and steel pointing at an obsidian block side.
